---
language: node_js
node_js:
- '0.10'
services:
- neo4j
before_script:
- npm install -g grunt-cli
addons:
  sauce_connect: true
deploy:
  provider: heroku
  app: agilejs-typesafe
  strategy: git
  api_key:
    secure: ! 'CEFm3Z+7Sq42uC6Dsuwv9dbYcrpfCAadNEBHk9F03YTFXg9ntLzGMdqRnuxC

      nK11XP1BAo4j4AyVKaFWM/CgEXGPREngzC/IA2QTJdKsK4zluxsAAPBQfUot

      /2RrCdLbjLqt6Qk451vSbj+xwt+66Le1MZwUEBDY9YCt23Pw9GQ='
env:
  global:
  - secure: ZIkSzkMPPS6ExpnsFQkOSrAafog351ztce72pt57DvEXX1hhENVlh/4YMAqJJBp6hI0c8ctkkGTBsjESub8n/imv/SKkcKYgqE51t26shHDsgt7pAfOxv5Cre60z7kyyA4byu7IKBOeYHe/h9ykfKyuHizwMKM2LwIUxk/WA59s=
  - secure: YWQH74gN5KY31vbz4meZ8vu6tNXNl3AXh88w0X3mT95oCv10tjjjRJuCCiFdXaWLY9x8g1B7EAIL9ddsqWH4UIWs+WU82Cw/Gymc2DH3ncsq3AFZZy2kLTVO+C9Q7jh2neDBnaKu483PVjlYpgfhwz3vnG8gQFX9uFBOLvMhtqQ=
