language: node_js
node_js:
- '0.10'
services:
- neo4j
before_script:
- npm install -g grunt-cli
addons:
  sauce_connect: true
deploy:
  provider: heroku
  app: movie-database-node
  api_key:
    secure: LfX4hB0xQv9z4ZD+Iiz0tffiNceHyB4/wfeFacra7m9xLpjtpqOmBvbQGzl3 3EGek2clup/ri2RHHQm5QCqK5L8ohptvHSoBusghHmXyV80knIb8mlnpmwMe
      7Vs7v9wdALHudWPHly9pN0OZHxYsRprQc8R6b2rowAdMxzMraDg=
env:
  global:
  - secure: ZIkSzkMPPS6ExpnsFQkOSrAafog351ztce72pt57DvEXX1hhENVlh/4YMAqJJBp6hI0c8ctkkGTBsjESub8n/imv/SKkcKYgqE51t26shHDsgt7pAfOxv5Cre60z7kyyA4byu7IKBOeYHe/h9ykfKyuHizwMKM2LwIUxk/WA59s=
  - secure: YWQH74gN5KY31vbz4meZ8vu6tNXNl3AXh88w0X3mT95oCv10tjjjRJuCCiFdXaWLY9x8g1B7EAIL9ddsqWH4UIWs+WU82Cw/Gymc2DH3ncsq3AFZZy2kLTVO+C9Q7jh2neDBnaKu483PVjlYpgfhwz3vnG8gQFX9uFBOLvMhtqQ=
